<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>

    </head>
    <body>

    <?php
    if ($_SESSION['user']['username'] != "") {
        echo "<p>" . $_SESSION['user']['username'] . "でログインしています" . "</p>";
    }else{
        echo "<p>"."ログインしていません"."</p>";
    }
    ?>


    <h1>login</h1>

        <form action="login" method="post">

            <input type="text" name="name" placeholder="name" required><br>
            <input type="password" name="pwd" placeholder="password" required>
            <input type="submit" value="send">

        </form>
        <a href="register">register</a><br>



        <?php


        $user = 'ryu';
        $password = 'ryuryu1207';
        $dbname = 'slimapp';
        $host = '127.0.0.1:3306';
        $dsn = "mysql:host={$host};dbname={$dbname};charset=utf8";
        //$mysqli = new mysqli($host,$user,$password,$dbname);
        try{
            $pdo = new PDO($dsn,$user,$password);
            $pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES,false);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            echo "DB{$dbname} 接続しました";
            $pdo = null;
        } catch (Exception $e){
            echo 'エラーです';
            echo $e->getMessage();
            exit();
        }
        ?>


    </body>
</html>
