<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>register
    <form action="/register" method="post">
        <input type="text" placeholder="name" name="name" required>
        <input type="text" placeholder="abcd@efgh.ijk" name="addles" required>
        <input type="password" placeholder="password" name="pwd" required>
        <input type="submit" value="send">
        
    </form>
</body>
</html>